---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cities
  namespace: {{ .Release.Namespace }}
data:
  cities.yaml: |
    cities:
      - name: Potsdam
        countryCode: DE
      - name: Bad Segeberg
        countryCode: DE
    defaultCity:
      name: Potsdam
      countryCode: DE
