---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-tokens
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  openweather_api_token: {{ .Values.openweatherApiToken | b64enc }}
